### PR TITLE
fix: fixed issue where null value would result in expression not bein…

### LINKED ISSUE #26: Error | Cannot read property 'expression' of null
Caused By:
https://github.com/coderas/babel-plugin-jsx-remove-data-test-id/blob/master/src/index.js#L72-L74

If `value` is `null` it will not hit the default assignment to `{}` which causes the error: 
```
Cannot read property 'expression' of  @null
```

Fails When an element with a boolean attribute exists
```jsx
<Hello someBoolean />
```

### PR DESCRIPTION
**Pull request by GoPro16**
fixes #26

### CODE REVIEW

**Comment by coderas** [comment]
Thanks for the contribution - I have a couple of observations:

- If the value is `null` I suspect the default of `{}` not to be set, i.e. the value is still `null`
- could we have tests?
- finally, some of the code style changes are fine, but can you keep the single quotes as they are please?

File: src/index.js [hunk 1]
```diff
@@ -68,25 +72,24 @@ const RemoveDataTestIds = ({ types: t }) => {
 
       const isObjectDefined = value => Object.keys(value).length !== 0;
 
-      const matchAndReplaceValues = currentAttr => {
-        const {
-          value: { expression: { properties = [] } = {} } = {}
-        } = currentAttr;
+      const matchAndReplaceValues = ({ value, ...currentAttr }) => {
+        const { expression: { properties = [] } = {} } = value || {};
```
Comment (coderas) [inline src/index.js]: I feel like this version would work.

**Comment by GoPro16** [comment]
> If the value is null I suspect the default of {} not to be set, i.e. the value is still null
Should be solid since we are doing the `|| {}`

> could we have tests?
Will Do.

>finally, some of the code style changes are fine, but can you keep the single quotes as they are please?
Assuming you mean not destructuring the params in the function declaration? If so I can change that.

**Comment by coderas** [comment]
> Should be solid since we are doing the || {}

I'm confused, I saw that on the first commit (and did a commit comment) but then it got replaced by:

```javascript
      const matchAndReplaceValues = ({ value = {}, ...currentAttr }) => {
      const { expression: { properties = [] } = {} } = value;
```

... Am I missing something (probably 🤣 )

**Comment by GoPro16** [comment]
Oh lol I didn't even see that my linter auto updated the quotes which was why I was confused.

File: tests/remove-data-test-id.spec.js [hunk 2]
```diff
@@ -110,6 +110,14 @@ const runTests = (label, transform) => {
           const expected = transform(expectedCode);
           expect(uglify(actual)).to.equal(uglify(expected));
         });
+
+        it('removes options.attributes null', () => {
```
Comment (coderas) [inline tests/remove-data-test-id.spec.js]: 👍

Comment (GoPro16) [reply tests/remove-data-test-id.spec.js]: I don' t think this solved the test bc I was able to add that to `master` and the test had passed without my changes. I need to look into this more rq before its merged.

Comment (coderas) [reply tests/remove-data-test-id.spec.js]: Ok, no worries - ping me when ready

Comment (GoPro16) [reply tests/remove-data-test-id.spec.js]: Should be working now. Updated original issue with the failing jsx.

File: tests/remove-data-test-id.spec.js [hunk 3]
```diff
@@ -70,7 +77,6 @@ const runTests = (label, transform) => {
 
         it('throws error when attributes is empty array', () => {
           const code = '<p selenium-id={false}></p>';
-          const expectedCode = '<p></p>';
```
Comment (GoPro16) [inline tests/remove-data-test-id.spec.js]: I just removed un used variables from here. Maybe I can add `eslint` to the project in another PR to provide rules for future changes so that everything follows a specified format?

Comment (mstruensee) [reply tests/remove-data-test-id.spec.js]: I was thinking the same thing (adding eslint) ... ticket created.  My formatter is also completely opposite of this repository :D

File: src/index.js [hunk 4]
```diff
@@ -68,25 +72,25 @@ const RemoveDataTestIds = ({ types: t }) => {
 
       const isObjectDefined = value => Object.keys(value).length !== 0;
 
-      const matchAndReplaceValues = currentAttr => {
-        const {
-          value: { expression: { properties = [] } = {} } = {}
-        } = currentAttr;
+      const matchAndReplaceValues = ({ value = {}, ...currentAttr }) => {
+        const { expression: { properties = [] } = {} } = value || {};
```
Comment (mstruensee) [inline src/index.js]: isn't value defaulted on line 75 `value = {}` so you shouldn't need `value || {}` on line 76 ??

Comment (GoPro16) [reply src/index.js]: Not necessarily because the default assignment only happens for values that are undefined. It does not run the default assignment if the value is null which is why I do that OR operation

Comment (mstruensee) [reply src/index.js]: ah right, gotta love javascript

File: tests/remove-data-test-id.spec.js (hunk 2 above)
Comment (coderas) [reply tests/remove-data-test-id.spec.js]: Sorry just got back online, seems good - going to go through publish now
